
// API 1
GET http://localhost:3001/players/

### API 2

GET http://localhost:3001/players/2/

### API 3
PUT http://localhost:3001/players/1/
Content-Type: application/json

{
    "playerName": "Ram"
}

### API 4

GET http://localhost:3001/matches/1/

### API 5
GET http://localhost:3001/players/18/matches/

### API 6

GET http://localhost:3001/matches/2/players/

### API 7

GET http://localhost:3001/players/1/playerScores/

### API 8

GET http://localhost:3001/matches/