
### 1
POST http://localhost:3001/login 
Content-Type: application/json

{
  "username": "christopher_phillips",
  "password": "christy@123"
}
### 2

GET http://localhost:3001/states/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjY3OTk3MDI5fQ.PoduJgMEZoln1Of4KiVjmmwDh_i1dTpbfvIpb5S75z0

### 3
GET http://localhost:3001/states/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjY3OTk3MDI5fQ.PoduJgMEZoln1Of4KiVjmmwDh_i1dTpbfvIpb5S75z0

### 4 
POST http://localhost:3001/districts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjY3OTk3MDI5fQ.PoduJgMEZoln1Of4KiVjmmwDh_i1dTpbfvIpb5S75z0
Content-Type: application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}
### 5

GET http://localhost:3001/districts/322/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjY3OTk3MDI5fQ.PoduJgMEZoln1Of4KiVjmmwDh_i1dTpbfvIpb5S75z0


### 7
PUT http://localhost:3001/districts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjY3OTk3MDI5fQ.PoduJgMEZoln1Of4KiVjmmwDh_i1dTpbfvIpb5S75z0
Content-Type: application/json

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

### 8
